# Generated by Django 5.1.2 on 2024-10-20 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sample_plate_barcode_sample_well_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplesignal',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='api.sample'),
        ),
    ]
